POS_BeautySalon/POS_BeautySalon/Controllers/CarritoController.cs
using DAL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace POS_BeautySalon.Controllers
{
    public class CarritoController : Controller
    {
        private readonly SalonContext _salonContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public CarritoController(SalonContext salonContext, UserManager<ApplicationUser> userManager)
        {
            _salonContext = salonContext;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var carrito = ObtenerCarritoDelUsuarioActual();
            var productosEnCarrito = _salonContext.CarritoProductos
                .Include(cp => cp.Producto)
                .Where(cp => cp.CarritoId == carrito.CarritoId)
                .ToList();

            //Calcular el total del carrito
            var total = carrito.CalcularTotal();

            //Pasar el valor Total a la vista
            ViewBag.Total = total;

            return View(productosEnCarrito);
        }

        //Método para agregar productos al carrito
        public async Task<IActionResult> AgregarAlCarrito(int productoId)
        {
            var carrito = ObtenerCarritoDelUsuarioActual();
            var producto = await _salonContext.Productos.FindAsync(productoId);

            if(producto.Cantidad < 1)
            {
                TempData["Error"] = "Este producto está agotado";
                return RedirectToAction(nameof(Index));
            }

            if(producto.Estado == 0)
            {
                TempData["Error"] = "Este producto no está disponible hasta dentro de 2 semanas";
                return RedirectToAction(nameof(Index));
            }

            var carritoProducto = new CarritoProducto
            {
                CarritoId = carrito.CarritoId,
                ProductoId = productoId,
                Cantidad = 1
            };

            producto.Cantidad -= 1;

            // Verificar si la cantidad del producto es igual o menor a 5
            if (producto.Cantidad <= 5)
            {
                producto.Alerta = $"Alerta! Quedan pocas unidades de {producto.Nombre}";
            }
            else if(producto.Cantidad > 5)
            {
                producto.Alerta = null;
            }

            // Actualizar el estado del producto si se agota
            producto.Estado = producto.Cantidad == 0 ? 0 : 1;

            _salonContext.Add(carritoProducto);
            _salonContext.Update(producto);
            await _salonContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //Método para editar cantidad de un producto del carrito
        public async Task<IActionResult> EditarCantidad(int carritoProductoId, int nuevaCantidad)
        {
            var carritoProducto = await _salonContext.CarritoProductos.FindAsync(carritoProductoId);
            var producto = await _salonContext.Productos.SingleAsync(p => p.ProductoId ==
            carritoProducto.ProductoId);

            if (producto.Cantidad < nuevaCantidad - carritoProducto.Cantidad)
            {
                TempData["Error"] = "La cantidad digitada excede la cantidad disponible de este producto.";
                return RedirectToAction(nameof(Index));
            }

            producto.Cantidad -= nuevaCantidad - carritoProducto.Cantidad;

            // Verificar si la cantidad del producto es igual o menor a 5
            if (producto.Cantidad <= 5)
            {
                producto.Alerta = $"Alerta! Quedan pocas unidades de {producto.Nombre}";
            }
            else if(producto.Cantidad > 5)
            {
                producto.Alerta = null;
            }

            // Actualizar el estado del producto si se agota
            producto.Estado = producto.Cantidad == 0 ? 0 : 1;

            carritoProducto.Cantidad = nuevaCantidad;

            _salonContext.Update(carritoProducto);
            _salonContext.Update(producto);
            await _salonContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //Método para eliminar un producto del carrito
        public async Task<IActionResult> EliminarDelCarrito(int carritoProductoId)
        {
            var carritoProducto = await _salonContext.CarritoProductos.FindAsync(carritoProductoId);
            var producto = await _salonContext.Productos.FindAsync(carritoProducto.ProductoId);

            // Incrementar la cantidad del producto en el inventario tras eliminar
            producto.Cantidad += carritoProducto.Cantidad;

            // Verificar si la cantidad del producto es igual o menor a 5
            if (producto.Cantidad <= 5)
            {
                TempData["Alerta"] = $"Alerta! Quedan pocas unidades de {producto.Nombre}";
            }

            _salonContext.CarritoProductos.Remove(carritoProducto);
            _salonContext.Update(producto);
            await _salonContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //Método complementario para obtener el carrito del usuario autenticado
        private Carrito ObtenerCarritoDelUsuarioActual()
        {
            var clienteId = _userManager.GetUserId(User);
            var carrito = _salonContext.Carritos.FirstOrDefault(c => c.ClienteId == clienteId);

            if (carrito == null)
            {
                carrito = new Carrito { ClienteId = clienteId };
                _salonContext.Carritos.Add(carrito);
                _salonContext.SaveChanges();
            }
            return carrito;
        }

        //Método para imprimir la factura
        public IActionResult ImprimirFactura()
        {
            var carrito = ObtenerCarritoDelUsuarioActual();
            var productosEnCarrito = _salonContext.CarritoProductos
                .Include(cp => cp.Producto)
                .Where(cp => cp.CarritoId == carrito.CarritoId)
                .ToList();

            var total = carrito.CalcularTotal();
            var consecutivo = GenerarConsecutivo();

            // Pasar los detalles de la factura a la vista
            ViewBag.ProductosEnCarrito = productosEnCarrito;
            ViewBag.Total = total;
            ViewBag.Consecutivo = consecutivo;

            return View("ImprimirFactura");
        }

       


        private int GenerarConsecutivo()
        {
            // Obtener el último ID de factura en la base de datos
            var ultimoIdFactura = _salonContext.Facturas
                                  .OrderByDescending(f => f.FacturaId)
                                  .Select(f => f.FacturaId)
                                  .FirstOrDefault();

            // Sumarle 1 para generar el nuevo consecutivo
            return ultimoIdFactura + 1;
        }



        //Compra de productos en carrito
        [HttpPost]
        public async Task<IActionResult> ConfirmarCompra(string metodoPago, string consecutivo)
        {
            if ((metodoPago == "Transferencia" || metodoPago == "Sinpe") && string.IsNullOrEmpty(consecutivo))
            {
                return Json(new { success = false, message = "El número de consecutivo es requerido para el método de pago seleccionado." });
            }

            var carrito = ObtenerCarritoDelUsuarioActual();

            var productosEnCarrito = _salonContext.CarritoProductos
                .Include(cp => cp.Producto)
                .Where(cp => cp.CarritoId == carrito.CarritoId)
                .ToList();

            var total = carrito.CalcularTotal();


            //CAMBIO DE ZONA HORARIA DE UTC A MST AGREGADO
            var mountainTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time");
            var fechaMST = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, mountainTimeZone);

            // Crear una única factura
            var factura = new Factura
            {
                ClienteId = carrito.ClienteId,
                PrecioTotal = total,
                //Fecha = DateTime.Now, ASI ESTABA ANTES
                Fecha = fechaMST,
            };

            _salonContext.Facturas.Add(factura);
            await _salonContext.SaveChangesAsync();

            // Crear y guardar los detalles de la factura
            foreach (var item in productosEnCarrito)
            {
                var detalleFactura = new DetalleFactura
                {
                    FacturaId = factura.FacturaId,
                    ProductoId = item.ProductoId,
                    Cantidad = item.Cantidad,
                    PrecioUnitario = item.Producto.Precio
                };

                _salonContext.DetalleFacturas.Add(detalleFactura);
            }

            await _salonContext.SaveChangesAsync();


            // Limpiar el carrito
            _salonContext.CarritoProductos.RemoveRange(productosEnCarrito);
            await _salonContext.SaveChangesAsync();

           

            // Actualizar los puntos del programa lealtad al cliente
            var cliente = await _userManager.FindByIdAsync(carrito.ClienteId);
            if (cliente != null)
            {
                // Contar el número de facturas del cliente para saber si ya puede hacer uso del programa lealtad
                var numFacturas = _salonContext.Facturas.Count(f => f.ClienteId == carrito.ClienteId);

                if (numFacturas % 2 == 0) //Cuando tenga dos compras realizadas
                {
                    cliente.PuntosProgramaLealtad += 10; // Sumar 10 puntos
                    var updateResult = await _userManager.UpdateAsync(cliente);
                    if (!updateResult.Succeeded)
                    {
                        return Json(new { success = false, message = "Error al actualizar los puntos del cliente." });
                    }
                    await Task.Delay(5000); // Esperar 5 segundos

POS_BeautySalon/POS_BeautySalon/Views/Carrito/ImprimirFactura.cshtml
@using DAL

<br />
<div class="titulos_cat">
    <h1>FACTURA<br><p style="font-weight: normal; font-size: 20px">Consecutivo: @ViewBag.Consecutivo</p></h1>
</div>

<br />
<table>
    <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio Unitario</th>
    </tr>
    @foreach (var item in ViewBag.ProductosEnCarrito)
    {
        <tr>
            <td>@item.Producto.Nombre</td>
            <td>@item.Cantidad</td>
            <td>₡@item.Producto.Precio</td>
        </tr>
    }
    
    
    <tr>
        <td colspan="7" style="font-size: 20px; font-weight: bold;">Total: ₡@ViewBag.Total</td>
    </tr>
</table>
<br>
<br>
<a onclick="window.print()" class="btn btn-dark" asp-controller="Carrito" asp-action="ImprimirFactura">Imprimir factura</a>

POS_BeautySalon/POS_BeautySalon/Views/Carrito/Index.cshtml
@using DAL
@model List<CarritoProducto>

<!DOCTYPE html>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<br />
<br />
<!--Mensaje de error en caso de que se exceda la cantidad en inventario-->
@if(TempData["Error"] != null)
{
    <div class="alert alert-danger">
        @TempData["Error"]
    </div>
}

<h1 class="titulos_cat">CARRITO VIRTUAL</h1>

<br />
<br />
<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">Producto</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Imagen</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Precio Individual</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Producto.Nombre</td>
                <td>@item.Producto.Descripcion</td>
                <td>
                    @if (item.Producto.ImagenProducto != null && item.Producto.ImagenProducto.Length > 0)
                    {
                        <img src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Producto.ImagenProducto))" width="100" />
                    }
                    else
                    {
                        <span>No se cargo una imagen</span>
                    }
                </td>
                <td>@item.Cantidad</td>
                <td>₡@item.Producto.Precio</td>
                <td>
                    <form asp-controller="Carrito" asp-action="EditarCantidad" method="post">
                        <input type="hidden" name="carritoProductoId" value="@item.CarritoProductoId" />
                        <input type="number" name="nuevaCantidad" min="1" max="100" value="@item.Cantidad" style="width: 60px;"
                        class="cantidad" data-id="@item.CarritoProductoId" />
                        <br />
                        <br />
                        @* <button type="submit" style="background-color:pink; color: black;">Actualizar</button> *@
                    </form>
                    <br />
                    <a class="btn btn-dark" asp-controller="Carrito" asp-action="EliminarDelCarrito" asp-route-carritoProductoId="@item.CarritoProductoId">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7" style="font-size: 20px; font-weight: bold;">Total: ₡@ViewBag.Total</td>
        </tr>
    </tfoot>
</table>

<a class="btn btn-dark" asp-controller="Carrito" asp-action="ImprimirFactura">Generar factura</a>
<br />
<br />
<br />
<div class="registration-section" style="margin: unset">
<h3>Metodos de pago</h3>

<a class="btn btn-dark" id="pagoSinpe">Sinpe</a>
<a class="btn btn-dark" id="pagoTransferencia">Transferencia</a>

<div id="mensajePago"></div>

<br />

<div class="card" style="left: -20px;" id="infoPago">
    <div class="card-body">
        <!-- Aquí irá la información de pago -->
    </div>
</div>

<!-- Campo para el consecutivo de la transacción -->
<div id="consecutivoContainer" style="display: none;">
    <label for="consecutivo">Número de consecutivo:</label>
    <input type="text" id="consecutivo" name="consecutivo" class="form-control" style="width: 18rem;" required />
</div>

<!--Metodos de pago-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Div para mostrar mensajes de notificación -->
<div id="notification" class="alert" role="alert" style="display:none;"></div>

<script>
$(document).ready(function () {
    var metodoPago;

    function mostrarConsecutivo() {
        $("#consecutivoContainer").show();
    }

    function ocultarConsecutivo() {
        $("#consecutivoContainer").hide();
    }


    $("#pagoTransferencia").click(function () {
        var numeroCuenta = '2365 9865 3214 1254'; 
        var nombreDueno = 'Viviana Ruiz'; 
        $("#infoPago .card-body").html("<h5 class='card-title'>Información de pago</h5><h6 class='card-subtitle mb-2 text-body-secondary'>Transferencia Bancaria</h6><p>Número de cuenta BCR: " + numeroCuenta + "</p><p>A nombre de: " + nombreDueno + "</p>");
        mostrarConsecutivo();
        metodoPago = "Transferencia";
    });

    $("#pagoSinpe").click(function () {
        var numeroTelefono = '8525 3219';
        var nombre = 'Viviana Ruiz';
        var consecutivo = '@ViewBag.Consecutivo';
        $("#infoPago .card-body").html("<h5 class='card-title'>Información de pago</h5><h6 class='card-subtitle mb-2 text-body-secondary'>SINPE Móvil</h6><p>Número de teléfono: " + numeroTelefono + "</p><p>Nombre: " + nombre + "</p>");
        mostrarConsecutivo();
        metodoPago = "Sinpe";
    });

    @*$("#confirmarCompra").click(function () {
        if ((metodoPago === 'Transferencia' || metodoPago === 'Sinpe') && $("#consecutivo").val() === '') {
            $("#notification").removeClass("alert-success").addClass("alert-danger").text("Por favor ingrese el número de consecutivo.").show();
        } else {
            var consecutivo = $("#consecutivo").val();
            $.post('@Url.Action("ConfirmarCompra", "Carrito")', { metodoPago: metodoPago, consecutivo: consecutivo }, function (response) {
                if (response.success) {
                    $("#notification").removeClass("alert-danger").addClass("alert-success").text(response.message).show();
                    setTimeout(function () {
                        location.reload(); // Limpiar el carrito recargando la página después de un corto retraso
                    }, 2000);
                } else {
                    $("#notification").removeClass("alert-success").addClass("alert-danger").text(response.message).show();
                }
            });
        }
    });*@

                $("#confirmarCompra").click(function () {
                    if ((metodoPago === 'Transferencia' || metodoPago === 'Sinpe') && $("#consecutivo").val() === '') {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: 'Por favor ingrese el número de consecutivo.',
                            confirmButtonText: 'Aceptar'
                        });
                    } else {
                        var consecutivo = $("#consecutivo").val();
                        $.post('@Url.Action("ConfirmarCompra", "Carrito")', { metodoPago: metodoPago, consecutivo: consecutivo }, function (response) {
                            if (response.success) {
                                Swal.fire({
                                    icon: 'success',
                                    title: 'Compra Confirmada',
                                    text: response.message,
                                    confirmButtonText: 'Aceptar'
                                }).then((result) => {
                                    if (result.isConfirmed) {
                                        location.reload(); // Limpiar el carrito recargando la página después de confirmar
                                    }
                                });
                            } else {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Error',
                                    text: response.message,
                                    confirmButtonText: 'Aceptar'
                                });
                            }
                        });
                    }
                });

});
</script>


<a class="btn btn-dark" id="confirmarCompra">Confirmar Compra</a>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
$(document).ready(function () {
    $('.cantidad').change(function () {
        var nuevaCantidad = $(this).val();
        var carritoProductoId = $(this).data('id');

        $.ajax({
            url: '/Carrito/EditarCantidad',
            type: 'POST',
            data: { carritoProductoId: carritoProductoId, nuevaCantidad: nuevaCantidad },
            success: function (response) {
                // Actualizar la página después de un retraso para evitar problemas de recarga rápida
                setTimeout(function () {
                    location.reload();
                }, 1000);
            },
            error: function (response) {
                alert('Error al actualizar la cantidad.');
            }
        });
    });
});
</script>


</html>