POS_BeautySalon/POS_BeautySalon/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;

namespace POS_BeautySalon.Controllers
{
    public class ProductosController : Controller
    {
        private readonly SalonContext _context;

        public ProductosController(SalonContext context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            var salonContext = _context.Productos.Include(p => p.Categoria).Include(p => p.Marca).Include(p => p.Proveedor);
            return View(await salonContext.ToListAsync());
        }

        public async Task<IActionResult> CatalogoProd(string searchTerm, int? categoriaId)
        {
            
            var productos = _context.Productos
        .Include(p => p.Categoria)
        .Include(p => p.Marca)
        .Include(p => p.Proveedor)
        .AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                productos = productos.Where(p => p.Nombre.Contains(searchTerm));
            }

            if (categoriaId.HasValue)
            {
                productos = productos.Where(p => p.CategoriaId == categoriaId.Value);
            }

            var categorias = await _context.Categorias.ToListAsync();
            ViewBag.Categorias = new SelectList(categorias, "CategoriaId", "Descripcion", categoriaId);
            ViewData["searchTerm"] = searchTerm;

            return View(await productos.ToListAsync());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Marca)
                .Include(p => p.Proveedor)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Descripcion");
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "MarcaId", "Descripcion");
            ViewData["ProveedorId"] = new SelectList(_context.Proveedores, "ProveedorId", "Nombre");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoId,Nombre,Descripcion,ImagenProducto,Precio,PrecioProveedor,Estado,Cantidad,CategoriaId,MarcaId,ProveedorId")] Producto producto, IFormFile ImagenProducto)
        {
            if (ModelState.IsValid)
            {
                // Verificar si ya existe un producto con el mismo nombre
                var productoExistente = await _context.Productos.FirstOrDefaultAsync(p => p.Nombre == producto.Nombre);

                if(productoExistente != null)
                {
                    ModelState.AddModelError("Nombre", "Ya existe un producto con este nombre.");
                    return View(producto);
                }

                byte[]? imagen = null;

                if (ImagenProducto != null && ImagenProducto.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await ImagenProducto.CopyToAsync(memoryStream);
                        imagen = memoryStream.ToArray();
                    }
                }

                Producto prod = new Producto
                {
                    Nombre = producto.Nombre,
                    Descripcion = producto.Descripcion,
                    ImagenProducto = imagen,
                    Precio = producto.Precio,
                    PrecioProveedor = producto.PrecioProveedor,
                    Estado = 1,
                    Cantidad = producto.Cantidad,
                    CategoriaId = producto.CategoriaId,
                    MarcaId = producto.MarcaId,
                    ProveedorId = producto.ProveedorId
                };
                
                _context.Add(prod);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Descripcion", producto.CategoriaId);
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "MarcaId", "Descripcion", producto.MarcaId);
            ViewData["ProveedorId"] = new SelectList(_context.Proveedores, "ProveedorId", "Nombre", producto.ProveedorId);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Descripcion", producto.CategoriaId);
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "MarcaId", "Descripcion", producto.MarcaId);
            ViewData["ProveedorId"] = new SelectList(_context.Proveedores, "ProveedorId", "Nombre", producto.ProveedorId);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductoId,Nombre,Descripcion,Precio,PrecioProveedor,Estado,Cantidad,CategoriaId,MarcaId,ProveedorId")] Producto producto, IFormFile ImagenProducto)
        {
            if (id != producto.ProductoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Verificar si ya existe un producto con el mismo nombre
                var productoExistente = await _context.Productos
                    .FirstOrDefaultAsync(p => p.Nombre == producto.Nombre && p.ProductoId != id);

                if (productoExistente != null)
                {
                    ModelState.AddModelError("Nombre", "Ya existe un producto con este nombre.");
                    return View(producto);
                }

                try
                {
                    var productoDb = await _context.Productos.FindAsync(id);

                    if (productoDb == null)
                    {
                        return NotFound();
                    }

                    // Si no se sube una nueva imagen, mantenemos la imagen existente
                    if (ImagenProducto != null && ImagenProducto.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await ImagenProducto.CopyToAsync(memoryStream);
                            productoDb.ImagenProducto = memoryStream.ToArray();
                        }
                    }

                    // Actualizar otros campos del producto
                    productoDb.Nombre = producto.Nombre;
                    productoDb.Descripcion = producto.Descripcion;
                    productoDb.Precio = producto.Precio;
                    productoDb.PrecioProveedor = producto.PrecioProveedor;
                    productoDb.Cantidad = producto.Cantidad;
                    productoDb.CategoriaId = producto.CategoriaId;
                    productoDb.MarcaId = producto.MarcaId;
                    productoDb.ProveedorId = producto.ProveedorId;

                    // Cambiar estado a "agotado" si cantidad es 0
                    productoDb.Estado = producto.Cantidad <= 0 ? 0 : 1;

                    _context.Update(productoDb);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "CategoriaId", "Descripcion", producto.CategoriaId);
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "MarcaId", "Descripcion", producto.MarcaId);
            ViewData["ProveedorId"] = new SelectList(_context.Proveedores, "ProveedorId", "Nombre", producto.ProveedorId);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Marca)
                .Include(p => p.Proveedor)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

POS_BeautySalon/POS_BeautySalon/Views/Productos/CatalogoProd.cshtml
@model IEnumerable<DAL.Producto>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <br />
    

    <div class="contenedor-prod">
        <h1 style="font-weight: bold">PRODUCTOS</h1>
        <div class="contenedor-busq">
            <div class="busqueda">
                <form asp-controller="Productos" asp-action="CatalogoProd" method="get">
                    <input type="text" name="searchTerm" placeholder="Buscar..." value="@ViewData["searchTerm"]">
                    <select name="categoriaId" asp-items="ViewBag.Categorias">
                        <option value="">Todas las categorías</option>
                    </select>
                    <button class="w-70 btn btn-lg btn-dark">Buscar</button>
                </form>
            </div>
        </div>
    </div>

    <br />
    <div class='cards'>
        <div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in Model)
    {

                <div class="col">
                    <div class="card h-100">
                        @if (item.ImagenProducto !=null && item.ImagenProducto.Length>
                            0)
                        {
                            <img src="data:image/jpeg;base64,@(Convert.ToBase64String(item.ImagenProducto))" class="card-img-top" width="100" height="370"/>
                        }
                        else
                        {
                            <span>No se cargo una imagen</span>
                        }
                        <div class="card-body d-flex flex-column align-items-center justify-content-center">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.Nombre)</h5>

                            

                            <h6>Precio: ₡@Html.DisplayFor(modelItem => item.Precio)</h6>


                            <p class="card-text">
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </p>
                        </div>
                        <div class="text-center">
                            <a class="w-70 btn btn-lg  btn-dark" asp-controller="ListaDeseoProductos" asp-action="Create"
                               asp-route-productoId="@item.ProductoId">Agregar a lista de deseos</a>
                            <br />
                            <br />
                            <form asp-controller="Carrito" asp-action="AgregarAlCarrito" method="Post">
                                <input type="hidden" name="productoId" value="@item.ProductoId" />
                                <button type="submit" class="w-70 btn btn-lg  btn-dark"
                                        style="background-color:pink;
                                    color: black;">
                                    Agregar al carrito
                                </button>
                            </form>
                        </div>
                        <br />
                        <br />
                    </div>
                </div>
            
        
    }
        </div>
    </div>
</body>

@if (TempData["Warning"] != null)
{
    <div class="alert alert-warning">
        @TempData["Warning"]
    </div>
}

POS_BeautySalon/POS_BeautySalon/Views/Productos/Create.cshtml
@model DAL.Producto

@{
    ViewData["Title"] = "Crear Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row fondoTransparente">
    <h1>Crear Producto</h1>
    <hr />
    <br />
        <div class="col-md-7">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nombre" class="form-label">Nombre del Producto</label>
                    <input asp-for="Nombre" class="form-control" placeholder="Ingrese el nombre del producto" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger"})
                </div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="form-label">Descripción del Producto</label>
                    <textarea asp-for="Descripcion" class="form-control" rows="3" placeholder="Ingrese la descripción del producto"></textarea>
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="ImagenProducto" class="form-label">Imagen del Producto</label>
                    <input type="file" accept="image/png" class="form-control" name="ImagenProducto" />
                </div>
                <div class="form-group">
                    <label asp-for="Precio" class="form-label">Precio de Venta</label>
                    <input asp-for="Precio" class="form-control" placeholder="Ingrese el precio de venta del producto" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PrecioProveedor" class="form-label">Precio de Compra</label>
                    <input asp-for="PrecioProveedor" class="form-control" placeholder="Ingrese el precio de compra del producto" />
                    <span asp-validation-for="PrecioProveedor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoriaId" class="form-label">Categoría del Producto</label>
                    <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.CategoriaId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="MarcaId" class="form-label">Marca del Producto</label>
                    <select asp-for="MarcaId" class="form-control" asp-items="ViewBag.MarcaId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="ProveedorId" class="form-label">Proveedor del Producto</label>
                    <select asp-for="ProveedorId" class="form-control" asp-items="ViewBag.ProveedorId"></select>
                </div>
                <div class="text-center">
                <input type="submit" style="background-color:pink; color: black;" value="Crear" class="w-50 btn btn-lg  btn-dark" />
                <a asp-action="Index" class="w-100 btn btn-lg btn-dark">Volver a la lista</a>
                </div>
            </form>
        </div>
 
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS_BeautySalon/POS_BeautySalon/Views/Productos/Delete.cshtml
@model DAL.Producto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="home">
    <h3>¿Seguro que quieres eliminar este producto?</h3>
    <hr />
    <br />
    <dl class="row" style="font-size: 20px; padding-left: 85px">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagenProducto)
        </dt>
        <dd class="col-sm-10">
            @if (Model.ImagenProducto != null && Model.ImagenProducto.Length > 0)
            {
                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.ImagenProducto))" width="150" />
            }
            else
            {
                <span>No se cargo una imagen</span>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Estado == 1)
            {
                <span class="text-success">Activo</span>
            }
            else
            {
                <span class="text-danger">Desactivado</span>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor.Nombre)
        </dd>
    </dl>
    <br />
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductoId" />
        <input type="submit" value="Eliminar" class="w-100 btn btn-lg  btn-dark" />
        <br />
        <br />
        <a class="w-100 btn btn-lg  btn-dark" style="background-color:pink; color: black;" asp-action="Index">Volver a la lista</a>
    </form>
</div>

POS_BeautySalon/POS_BeautySalon/Views/Productos/Details.cshtml
@model DAL.Producto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class ="home">
    <h2>Producto</h2>
    <hr />
    <br />
    <dl class="row" style="font-size: 20px; padding-left: 85px">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.ImagenProducto)
        </dt>
        <dd class="col-sm-7">
            @if (Model.ImagenProducto != null && Model.ImagenProducto.Length > 0)
            {
                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.ImagenProducto))" width="150" />
            }
            else
            {
                <span>No se cargo una imagen</span>
            }
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-7">
            @if (Model.Estado == 1)
            {
                <span class="text-success">Activo</span>
            }
            else
            {
                <span class="text-danger">Desactivado</span>
            }
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Marca.Descripcion)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Proveedor.Nombre)
        </dd>
    </dl>
    <div>
        <a class="w-100 btn btn-lg  btn-dark" asp-action="Edit" asp-route-id="@Model?.ProductoId">Editar</a>
        <br />
        <br />
        <a class="w-100 btn btn-lg  btn-dark" style="background-color:pink; color: black;" asp-action="Index">Volver a la lista</a>
    </div>
</div>

POS_BeautySalon/POS_BeautySalon/Views/Productos/Edit.cshtml
@model DAL.Producto

@{
    ViewData["Title"] = "Editar Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row registration-section">
    <h2>Editar Producto</h2>
    <div class="row">
        <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ProductoId" />
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="ImagenProducto" class="form-label">Imagen del Producto</label>
                    <input type="file" accept="image/png" class="form-control" name="ImagenProducto" />
                </div>
                <div class="form-group">
                    <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PrecioProveedor" class="control-label"></label>
                    <input asp-for="PrecioProveedor" class="form-control" />
                    <span asp-validation-for="PrecioProveedor" class="text-danger"></span>
                </div>                
                <div class="form-group">
                        <label asp-for="Estado"></label>
                        <select asp-for="Estado" class="form-control">
                            <option value="1" selected="@Model.Estado == 1">Activo</option>
                            <option value="0" selected="@Model.Estado == 0">Desactivado</option>
                        </select>
                        <span asp-validation-for="Estado" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cantidad" class="control-label"></label>
                    <input asp-for="Cantidad" class="form-control" />
                    <span asp-validation-for="Cantidad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoriaId" class="control-label"></label>
                    <select asp-for="CategoriaId" class="form-control" asp-items="ViewBag.CategoriaId"></select>
                    <span asp-validation-for="CategoriaId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MarcaId" class="control-label"></label>
                    <select asp-for="MarcaId" class="form-control" asp-items="ViewBag.MarcaId"></select>
                    <span asp-validation-for="MarcaId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProveedorId" class="control-label"></label>
                    <select asp-for="ProveedorId" class="form-control" asp-items="ViewBag.ProveedorId"></select>
                    <span asp-validation-for="ProveedorId" class="text-danger"></span>
                </div>
                <br />
                <div class="text-center">
                <input type="submit" value="Guardar" class="w-50 btn btn-lg  btn-dark" />
                <br />
                <br />
                <a class="w-100 btn btn-lg  btn-dark" style="background-color:pink; color: black;" asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
                </div>
            </form>
    </div>

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS_BeautySalon/POS_BeautySalon/Views/Productos/Index.cshtml
@model IEnumerable<DAL.Producto>

@{
    ViewData["Title"] = "Inventario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@* Mensaje de alerta que se mostrará cuando la cantidad sea menor o igual a 5 *@
<br />
<h1 class="titulos_cat">INVENTARIO</h1>
<br />


@foreach (var item in Model)
{
    if (item.Cantidad <= 5 && item.Estado == 1)
    {
        <div class="alert alert-warning">
            El producto @item.Nombre tiene pocas existencias (@item.Cantidad unidades restantes).
        </div>
    }
    else if (item.Estado == 0)
    {
        <div class="alert alert-danger">
            El producto @item.Nombre está agotado.
        </div>
    }
}

<table>
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Descripcion)</th>
            <th>@Html.DisplayNameFor(model => model.ImagenProducto)</th>
            <th>Precio de venta</th>
            <th>@Html.DisplayNameFor(model => model.PrecioProveedor)</th>
            <th>@Html.DisplayNameFor(model => model.Cantidad)</th>
            <th>@Html.DisplayNameFor(model => model.Categoria)</th>
            <th>@Html.DisplayNameFor(model => model.Marca)</th>
            <th>@Html.DisplayNameFor(model => model.Proveedor)</th>
            <th>Acciones</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                <td>
                    @if (item.ImagenProducto != null && item.ImagenProducto.Length > 0)
                    {
                        <img src="data:image/jpeg;base64,@(Convert.ToBase64String(item.ImagenProducto))" width="100" />
                    }
                    else
                    {
                        <span class="text-muted">No se cargó una imagen</span>
                    }
                </td>
                <td>₡@Html.DisplayFor(modelItem => item.Precio)</td>
                <td>₡@Html.DisplayFor(modelItem => item.PrecioProveedor)</td>
                <td>@Html.DisplayFor(modelItem => item.Cantidad)</td>
                <td>@Html.DisplayFor(modelItem => item.Categoria.Descripcion)</td>
                <td>@Html.DisplayFor(modelItem => item.Marca.Descripcion)</td>
                <td>@Html.DisplayFor(modelItem => item.Proveedor.Nombre)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProductoId">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.ProductoId">Detalles</a>
                    <a asp-action="Delete" asp-route-id="@item.ProductoId">Eliminar</a>
                    <form asp-controller="CarritoProveedores" asp-action="AgregarProdProveedor" method="Post">
                        <input type="hidden" name="productoId" value="@item.ProductoId" />
                        <button type="submit" class="w-70 btn-dark"
                                style="background-color:pink;
                                    color: black;">
                            Agregar pedido
                        </button>
                    </form>
                </td>
                <td>
                    @if (item.Estado == 0)
                    {
                        <span class="badge bg-danger">Agotado</span>
                    }
                    else
                    {
                        <span class="badge bg-success">Disponible</span>
                    }
                    <form asp-action="ToggleAgotado" asp-route-id="@item.ProductoId" method="post">
                        <input type="checkbox" onchange="this.form.submit()" name="agotado" @(item.Estado == 0 ? "checked" : "") />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<br />
<p>
    <a asp-action="Create" class="w-70 btn btn-lg  btn-dark"
       style="background-color:pink; color: black;">Agregar nuevo producto</a>
</p>