POS_BeautySalon/POS_BeautySalon/Controllers/CarritoProveedoresController.cs
using DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace POS_BeautySalon.Controllers
{
    public class CarritoProveedoresController : Controller
    {
        private readonly SalonContext _salonContext;

        public CarritoProveedoresController(SalonContext salonContext)
        {
            _salonContext = salonContext;
        }

        public IActionResult Index()
        {
            var carritoProveedor = ObtenerCarritoEstilista();
            var productosEnCarrito = _salonContext.CarritoProvProductos
                .Include(cp => cp.Producto)
                .Where(cp => cp.CarritoProveedorId == carritoProveedor.CarritoProveedorId)
                .ToList();

            // Calcular el total del carrito
            var total = carritoProveedor.CalcularTotal();

            // Pasar el valor Total a la vista
            ViewBag.Total = total;

            return View(productosEnCarrito);
        }

        // Método para agregar productos al carrito
        public async Task<IActionResult> AgregarProdProveedor(int productoId)
        {
            var carritoProveedor = ObtenerCarritoEstilista();

            var carritoProvProducto = new CarritoProvProducto
            {
                CarritoProveedorId = carritoProveedor.CarritoProveedorId,
                ProductoId = productoId,
                Cantidad = 1
            };

            _salonContext.Add(carritoProvProducto);
            await _salonContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



        // Acción para mostrar las facturas de proveedores
        public async Task<IActionResult> VerFacturasProveedores()
        {
            var facturasProveedores = await _salonContext.FacturaProveedores
                .Include(f => f.Proveedor)
                .Include(f => f.DetalleProveedorFacturas)
                .ThenInclude(d => d.Producto)
                .ToListAsync();

            return PartialView("FacturasProveedores", facturasProveedores);
        }


        //Accion para ver Detalles de la factura 
        public async Task<IActionResult> VerDetallesProveedorFactura(int facturaProveedorId)
        {
            var detallesFactura = await _salonContext.DetalleProveedorFacturas
                .Include(d => d.Producto)
                .ThenInclude(p => p.Marca)
                .Include(d => d.Producto)
                .ThenInclude(p => p.Categoria)
                .Where(d => d.FacturaProveedorId == facturaProveedorId)
                .ToListAsync();

            ViewBag.FacturaProveedorId = facturaProveedorId; // Para pasar el ID a la vista, si es necesario
            return View("DetallesProveedorFactura", detallesFactura);
        }

        //Eliminar Factura de proveedor, Vista FacturasProveedores
        [HttpPost]
        public async Task<IActionResult> EliminarFacturaProveedor(int facturaProveedorId)
        {
            var factura = await _salonContext.FacturaProveedores
                .Include(f => f.DetalleProveedorFacturas)
                .FirstOrDefaultAsync(f => f.FacturaProveedorId == facturaProveedorId);

            if (factura == null)
            {
                return NotFound();
            }

            // Elimina los detalles relacionados
            _salonContext.DetalleProveedorFacturas.RemoveRange(factura.DetalleProveedorFacturas);

            // Elimina la factura
            _salonContext.FacturaProveedores.Remove(factura);

            await _salonContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }




        // Método para editar cantidad de un producto del carrito
        public async Task<IActionResult> EditarCantidad(int carritoProvProductoId, int nuevaCantidad)
        {
            var carritoProvProducto = await _salonContext.CarritoProvProductos.FindAsync(carritoProvProductoId);

           
            carritoProvProducto.Cantidad = nuevaCantidad; // Actualizar la cantidad en el carrito

            _salonContext.Update(carritoProvProducto);
            await _salonContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // Método para eliminar un producto del carrito
        public async Task<IActionResult> EliminarDelCarrito(int carritoProvProductoId)
        {
            var carritoProvProducto = await _salonContext.CarritoProvProductos.FindAsync(carritoProvProductoId);

            _salonContext.CarritoProvProductos.Remove(carritoProvProducto);
            await _salonContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // Método complementario para obtener el carrito del estilista

        /*private CarritoProveedor ObtenerCarritoEstilista()
        {
            var carritoProveedor = _salonContext.CarritoProveedores.FirstOrDefault();

            if (carritoProveedor == null)
            {
                carritoProveedor = new CarritoProveedor();
                _salonContext.CarritoProveedores.Add(carritoProveedor);
                _salonContext.SaveChanges();
            }
            return carritoProveedor;
        }*/

        private CarritoProveedor ObtenerCarritoEstilista()
        {
            var carritoProveedor = _salonContext.CarritoProveedores.FirstOrDefault();

            if (carritoProveedor == null)
            {
                // Asigna un ProveedorId válido
                var proveedor = _salonContext.Proveedores.FirstOrDefault();
                if (proveedor == null)
                {
                    throw new InvalidOperationException("No hay proveedores disponibles.");
                }

                carritoProveedor = new CarritoProveedor
                {
                    ProveedorId = proveedor.ProveedorId
                };

                _salonContext.CarritoProveedores.Add(carritoProveedor);
                _salonContext.SaveChanges();
            }

            return carritoProveedor;
        }



        [HttpPost]
        public async Task<IActionResult> ConfirmarCompra()
        {
            
            var carritoProveedor = ObtenerCarritoEstilista();

            var productosEnCarrito = _salonContext.CarritoProvProductos
                .Include(cp => cp.Producto)
                .Where(cp => cp.CarritoProveedorId == carritoProveedor.CarritoProveedorId)
                .ToList();

            var total = carritoProveedor.CalcularTotal();


            //CAMBIO DE ZONA HORARIA DE UTC A MST AGREGADO
            var mountainTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time");
            var fechaMST = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, mountainTimeZone);

            // Crear una única factura
            var facturaProveedor = new FacturaProveedor
            {
                ProveedorId = carritoProveedor.ProveedorId,
                PrecioTotal = total,
                //Fecha = DateTime.Now, Asi estaba antes
                Fecha = fechaMST,
            };

            _salonContext.FacturaProveedores.Add(facturaProveedor);
            await _salonContext.SaveChangesAsync();

            // Crear y guardar los detalles de la factura
            foreach (var item in productosEnCarrito)
            {
                var detalleProveedorFactura = new DetalleProveedorFactura
                {
                    FacturaProveedorId = facturaProveedor.FacturaProveedorId,
                    ProductoId = item.ProductoId,
                    Cantidad = item.Cantidad,
                    PrecioUnitario = item.Producto.PrecioProveedor
                };

                _salonContext.DetalleProveedorFacturas.Add(detalleProveedorFactura);

                // Actualizar el inventario de productos
                var producto = await _salonContext.Productos.FindAsync(item.ProductoId);
                producto.Cantidad += item.Cantidad; // Incrementar la cantidad de productos en el inventario

                // Marcar producto como agotado si la cantidad es cero
                producto.Estado = producto.Cantidad <= 0 ? 0 : 1;

                _salonContext.Update(producto);
            }

            await _salonContext.SaveChangesAsync();

            // Limpiar el carrito
            _salonContext.CarritoProvProductos.RemoveRange(productosEnCarrito);
            await _salonContext.SaveChangesAsync();

            return Json(new { success = true, message = "Compra confirmada con éxito." });
        }
    }
}

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/AgregarProdProveedor.cshtml
@model DAL.CarritoProvProducto

@{
    ViewData["Title"] = "Agregar Producto al Carrito";
}

<h1>Agregar Producto al Carrito</h1>

<h4>Producto del Carrito</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AgregarProdProveedor">
            <div class="form-group">
                <label asp-for="ProductoId" class="control-label"></label>
                <select asp-for="ProductoId" class="form-control" asp-items="ViewBag.ProductoId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.CarritoProveedorId">Volver al carrito</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/Create.cshtml
@model DAL.CarritoProveedor

@{
    ViewData["Title"] = "Crear Carrito de Proveedor";
}

<h1>Crear Carrito de Proveedor</h1>

<h4>Carrito de Proveedor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="ProveedorId" class="control-label"></label>
                <select asp-for="ProveedorId" class="form-control" asp-items="ViewBag.ProveedorId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/Delete.cshtml
@model DAL.CarritoProveedor

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarritoProveedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarritoProveedorId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/Details.cshtml
@model DAL.CarritoProveedor

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>CarritoProveedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CarritoProveedorId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/DetallesProveedorFactura.cshtml
@model IEnumerable<DAL.DetalleProveedorFactura>


    <br>
    <br>
<table class="table">
    <thead class ="table-dark">
        <tr>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Precio Proveedor</th>
            <th>Precio de Venta</th>
            <th>Descripcion</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var detalle in Model)
        {
            <tr>
                <td>@detalle.Producto.Nombre</td>
                <td>
                    @if (detalle.Producto.ImagenProducto != null)
                    {
                        <img src="data:image;base64,@Convert.ToBase64String(detalle.Producto.ImagenProducto)" alt="Imagen Producto" style="width:100px; height:auto;" />
                    }
                </td>
                <td>@detalle.Producto.PrecioProveedor</td>
                <td>@detalle.Producto.Precio</td>
                <td>@detalle.Producto.Descripcion</td>
                
            </tr>
        }
    </tbody>
</table>

<a href="@Url.Action("Index", "CarritoProveedores")" class="btn btn-dark">Volver</a>

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/Edit.cshtml
@model DAL.CarritoProveedor

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>CarritoProveedor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarritoProveedorId" />
            <div class="form-group">
                <label asp-for="ProveedorId" class="control-label"></label>
                <select asp-for="ProveedorId" class="form-control" asp-items="ViewBag.ProveedorId"></select>
                <span asp-validation-for="ProveedorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/FacturasProveedores.cshtml
@model IEnumerable<DAL.FacturaProveedor>

<br>
<br>
<br>
<h1 class="titulos_cat">Facturas de Proveedores</h1>
<br>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th>Proveedor</th>
            <th>Fecha</th>
            <th>Precio Total</th>
            <th>Detalles</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var factura in Model)
        {
            <tr>
                <td>@factura.Proveedor.Nombre</td>
                <td>@factura.Fecha.ToShortDateString()</td>
                <td>@factura.PrecioTotal</td>
                <td>
                    <a href="@Url.Action("VerDetallesProveedorFactura", "CarritoProveedores", new { facturaProveedorId = factura.FacturaProveedorId })" class="w-5 btn btn-lg btn-dark"
                       style="background-color:pink; color: black;">
                        Ver Detalles
                    </a>
                </td>
                <td>
                    <form action="@Url.Action("EliminarFacturaProveedor", "CarritoProveedores", new { facturaProveedorId = factura.FacturaProveedorId })" method="post" onsubmit="return confirm('¿Estás seguro de que quieres eliminar esta factura?');">
                        <button type="submit" class="w-5 btn btn-lg btn-dark"
                                style="background-color:pink; color: black;">
                            Eliminar
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

POS_BeautySalon/POS_BeautySalon/Views/CarritoProveedores/Index.cshtml
@model IEnumerable<DAL.CarritoProvProducto>

<h2></h2>


<br />


<h1 class="titulos_cat">PRODUCTOS EN EL CARRITO</h1>

<br />
<br />
<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">Producto</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Imagen</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Precio Individual</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Producto.Nombre</td>
                <td>@item.Producto.Descripcion</td>
                <td>
                    @if (item.Producto.ImagenProducto != null && item.Producto.ImagenProducto.Length > 0)
                    {
                        <img src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Producto.ImagenProducto))" width="100" />
                    }
                    else
                    {
                        <span>No se cargo una imagen</span>
                    }
                </td>
                <td>@item.Cantidad</td>
                <td>₡@item.Producto.PrecioProveedor</td>
                <td>
                    <form asp-controller="CarritoProveedores" asp-action="EditarCantidad" method="post">
                        <input type="hidden" name="CarritoProvProductoId" value="@item.CarritoProvProductoId" />
                        <input type="number" name="nuevaCantidad" min="1" max="100" value="@item.Cantidad" style="width: 60px;"
                        class="cantidad" data-id="@item.CarritoProvProductoId" />
                        <br />
                        <br />
                        @* <button type="submit" style="background-color:pink; color: black;">Actualizar</button> *@
                    </form>
                    <br />
                    <a class="btn btn-dark" asp-controller="CarritoProveedores" asp-action="EliminarDelCarrito" asp-route-CarritoProvProductoId="@item.CarritoProvProductoId">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7" style="font-size: 20px; font-weight: bold;">Total: ₡@ViewBag.Total</td>
        </tr>
    </tfoot>
</table>




<br />
<br />


<!--Metodos de pago-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Div para mostrar mensajes de notificación -->
<div id="notification" class="alert" role="alert" style="display:none;"></div>

<script>
    $(document).ready(function () {
        $("#confirmarCompra").click(function () {
            $.post('@Url.Action("ConfirmarCompra", "CarritoProveedores")', function (response) {
                if (response.success) {
                    $("#notification").removeClass("alert-danger").addClass("alert-success").text(response.message).show();
                    setTimeout(function () {
                        location.reload(); // Limpiar el carrito recargando la página después de un corto retraso
                    }, 2000);
                } else {
                    $("#notification").removeClass("alert-success").addClass("alert-danger").text(response.message).show();
                }
            });
        });
    });
</script>



<a class="btn btn-dark" id="confirmarCompra">Confirmar Pedido</a>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('.cantidad').change(function () {
            var nuevaCantidad = $(this).val();
            var carritoProvProductoId = $(this).data('id');

            $.ajax({
                url: '/CarritoProveedores/EditarCantidad',
                type: 'POST',
                data: { carritoProvProductoId: carritoProvProductoId, nuevaCantidad: nuevaCantidad },
                success: function (response) {
                    // Actualizar la página
                    location.reload();
                },
                error: function (response) {
                    alert('Error al actualizar la cantidad.');
                }
            });
        });
    });
</script>

<!-- Botón para ver las facturas de proveedores -->
<button id="verFacturasProveedores" class="btn btn-dark">Ver Facturas de Proveedores</button>

<div id="facturasProveedoresContainer"></div>


@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#verFacturasProveedores').click(function () {
                $.ajax({
                    url: '@Url.Action("VerFacturasProveedores", "CarritoProveedores")',
                    type: 'GET',
                    success: function (data) {
                        $('#facturasProveedoresContainer').html(data);
                    },
                    error: function () {
                        alert('Error al cargar las facturas de proveedores.');
                    }
                });
            });
        });
    </script>
}