POS_BeautySalon/POS_BeautySalon/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using DAL.Migrations.Salon;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace POS_BeautySalon.Controllers
{
    public class CitasController : Controller
    {
        private readonly SalonContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;
        private readonly IConfiguration _configuration;

        public CitasController(SalonContext context, UserManager<ApplicationUser> userManager, IEmailSender emailSender, IConfiguration configuration)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
            _configuration = configuration;
        }

        // GET: Citas
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userRoles = _userManager.GetRolesAsync(_userManager.FindByIdAsync(userId).Result).Result;

            if (userRoles.Contains("Cliente"))
            {
                var salonContext = _context.Citas
                    .Where(c => c.ClienteId == userId)
                    .Include(c => c.Cliente)
                    .Include(c => c.Servicio).ToList(); ;
                //return View(await salonContext.ToListAsync());

                var citasPasadas = salonContext.Where(c => c.Fecha < DateTime.Today).ToList();
                var citasFuturas = salonContext.Where(c => c.Fecha > DateTime.Today).ToList();
                var citasDelDia = salonContext.Where(c => c.Fecha == DateTime.Today).ToList();

                ViewData["CitasPasadas"] = citasPasadas;
                ViewData["CitasFuturas"] = citasFuturas;
                ViewData["CitasDelDia"] = citasDelDia;
            }
            else
            {
                var salonContext = _context.Citas
                    .Include(c => c.Cliente)
                    .Include(c => c.Servicio).ToList(); ;
                //return View(await salonContext.ToListAsync());

                var citasPasadas = salonContext.Where(c => c.Fecha < DateTime.Today).ToList();
                var citasFuturas = salonContext.Where(c => c.Fecha > DateTime.Today).ToList();
                var citasDelDia = salonContext.Where(c => c.Fecha == DateTime.Today).ToList();

                ViewData["CitasPasadas"] = citasPasadas;
                ViewData["CitasFuturas"] = citasFuturas;
                ViewData["CitasDelDia"] = citasDelDia;
            }

            return View();

        }

        // GET: Citas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Citas
                .Include(c => c.Cliente)
                .Include(c => c.Servicio)
                .FirstOrDefaultAsync(m => m.CitaId == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // GET: Citas/Create
        public async Task<IActionResult> CreateAsync(int servicioId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            if (User.IsInRole("Administrador") || User.IsInRole("Estilista"))
            {
                // Mostrar todos los clientes
                var usuariosCliente = await _userManager.GetUsersInRoleAsync("Cliente");
                ViewBag.ClienteId = new SelectList(
            usuariosCliente.Select(u => new
            {
                Id = u.Id,
                NombreCompleto = $"{u.Nombre} {u.Apellido}"
            }).ToList(),
            "Id",
            "NombreCompleto"
        );
            }
            else if (User.IsInRole("Cliente"))
            {
                // Mostrar solo el cliente actualmente logueado
                var cliente = await _userManager.FindByIdAsync(userId);
                ViewBag.ClienteId = new SelectList(
            new List<ApplicationUser> { cliente }.Select(u => new
            {
                Id = u.Id,
                NombreCompleto = $"{u.Nombre} {u.Apellido}"
            }).ToList(),
            "Id",
            "NombreCompleto"
        );
            }

            // Mostrar todos los servicios
            ViewBag.ServicioId = new SelectList(await _context.Servicios.ToListAsync(), "ServicioId", "Nombre");

            var cita = new Cita
            {
                ServicioId = servicioId
            };

            return View(cita);
        }


        // POST: Citas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create([Bind("CitaId,Estado,ClienteId,ServicioId,Fecha,Hora,Notas,FacturaId")] Cita cita)
        {
            var identidad = User.Identity as ClaimsIdentity;
            string idUsuarioLogeado = identidad.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;

            if (!User.IsInRole("Administrador") && !User.IsInRole("Estilista"))
            {
                cita.ClienteId = idUsuarioLogeado;
            }

            cita.Estado = 1;

            if (ModelState.IsValid)
            {
                if (cita.Fecha < DateTime.Today)
                {
                    ModelState.AddModelError("", "No se pueden programar citas en fechas anteriores a la fecha actual.");
                }
                else if (cita.Fecha.DayOfWeek == DayOfWeek.Sunday ||
                         cita.Hora.TimeOfDay < new TimeSpan(7, 0, 0) ||
                         cita.Hora.TimeOfDay >= new TimeSpan(19, 0, 0))
                {
                    ModelState.AddModelError("", "Las citas solo se pueden programar de lunes a sábado, entre las 7 am y las 7 pm.");
                }
                else
                {
                    TimeSpan citaDuracion = new TimeSpan(2, 0, 0);
                    DateTime citaFin = cita.Hora.Add(citaDuracion);
                    var citasDelDia = _context.Citas.Where(c => c.Fecha == cita.Fecha).ToList();
                    var conflictingCitas = citasDelDia
                        .Where(c => (c.Hora < citaFin && c.Hora.Add(citaDuracion) > cita.Hora) || (c.Hora < cita.Hora && c.Hora.Add(citaDuracion) > cita.Hora))
                        .ToList();

                    if (conflictingCitas.Any())
                    {
                        ModelState.AddModelError("", "Ya existe una cita programada en el mismo horario o dentro del intervalo de 2 horas.");
                    }
                    else
                    {
                        _context.Add(cita);
                        await _context.SaveChangesAsync();

                        // Crear la factura
                        var servicio = await _context.Servicios.FindAsync(cita.ServicioId);
                        var factura = new Factura
                        {
                            ClienteId = cita.ClienteId,
                            PrecioTotal = servicio.Precio,
                            Fecha = DateTime.Now
                        };

                        _context.Add(factura);
                        await _context.SaveChangesAsync();

                        // Crear el detalle de la factura
                        var detalleFactura = new DetalleFactura
                        {
                            FacturaId = factura.FacturaId,
                            ServicioId = cita.ServicioId,
                            PrecioUnitario = servicio.Precio
                        };

                        _context.Add(detalleFactura);
                        await _context.SaveChangesAsync();

                        // Vincular la cita con la factura
                        cita.FacturaId = factura.FacturaId;
                        _context.Update(cita);
                        await _context.SaveChangesAsync();

                        // Enviar correo de confirmación
                        var cliente = await _userManager.FindByIdAsync(cita.ClienteId);
                        var estilistaEmail = _configuration["Estilista:Email"];

                        if (cliente != null && !string.IsNullOrWhiteSpace(cliente.Email))
                        {
                            var emailContent = $@"
            <p>Hola {cliente.Nombre},</p>
            <p>Código de reserva: {cita.CitaId}</p>
            <p>Tu cita para el servicio {servicio.Nombre} ha sido agendada para el {cita.Fecha:dd/MM/yyyy} a las {cita.Hora:hh\:mm}.</p>
            <p>Notas: {cita.Notas}</p>
            <p>Gracias por elegirnos!</p>";
                            try
                            {
                                await _emailSender.SendEmailAsync(cliente.Email, "Confirmación de Cita", emailContent);
                            }
                            catch (Exception)
                            {
                                ModelState.AddModelError("", "Hubo un problema al enviar el correo de confirmación al cliente. Por favor, inténtalo de nuevo más tarde.");
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("", "No se pudo enviar el correo de confirmación porque la dirección de correo del cliente no es válida.");
                        }

                        if (!string.IsNullOrWhiteSpace(estilistaEmail))
                        {

POS_BeautySalon/POS_BeautySalon/Views/Citas/Create.cshtml
@model DAL.Cita

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var isAdmin = User.IsInRole("Administrador");
    var isCliente = User.IsInRole("Cliente");
    var isEstilista = User.IsInRole("Estilista");

    // Obtener la fecha y hora actual
    var currentDate = DateTime.Now.ToString("yyyy-MM-dd");
    var currentTime = DateTime.Now.ToString("HH:mm");
}



<div class="row fondoTransparente">
    <h1>Agendar Cita</h1>
    
    <hr />
    <br />
    <div class="col-md-7">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServicioId" class="control-label"></label>
                <select asp-for="ServicioId" class ="form-control" asp-items="ViewBag.ServicioId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" type="date" class="form-control" value="@currentDate" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hora" class="control-label"></label>
                <input asp-for="Hora" type="time" class="form-control" value="@currentTime" />
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notas" class="control-label"></label>
                <textarea asp-for="Notas" class="form-control"></textarea>
                <span asp-validation-for="Notas" class="text-danger"></span>
            </div>
            <div class="text-center">
                <input type="submit" style="background-color:pink; color: black;" value="Crear" class="w-50 btn btn-lg  btn-dark" />
                <a class="w-100 btn btn-lg btn-dark" asp-action="Index">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

POS_BeautySalon/POS_BeautySalon/Views/Citas/Delete.cshtml
@model DAL.Cita

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="home">
    <h3>¿Seguro que quieres eliminar esta cita?</h3>
    <hr />
    <br />
    <dl class="row" style="font-size: 20px; padding-left: 85px">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-7">
            @Html.Raw(Model.Fecha.ToString("dd/MM/yyyy"))
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Hora)
        </dt>
        <dd class = "col-sm-7">
            @Html.Raw(Model.Hora.ToString("hh\\:mm"))
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Servicio)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Servicio.Nombre)
        </dd>
    </dl>
    <br />
    <form asp-action="Delete">
        <input type="hidden" asp-for="CitaId" />
        <input type="submit" value="Eliminar" class="w-100 btn btn-lg  btn-dark" />
        <br />
        <br />
        <a class="w-100 btn btn-lg  btn-dark" style="background-color:pink; color: black;" asp-action="Index">Volver a la lista</a>
    </form>
</div>

POS_BeautySalon/POS_BeautySalon/Views/Citas/Details.cshtml
@model DAL.Cita

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="home">
    <h2>Cita</h2>
    <hr />
    <br />
    <dl class="row" style="font-size: 20px; padding-left: 85px">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class="col-sm-7">
            @Html.Raw(Model.Fecha.ToString("dd/MM/yyyy"))
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Hora)
        </dt>
        <dd class="col-sm-7">
            @Html.Raw(Model.Hora.ToString("hh\\:mm"))
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class="col-sm-7">
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Servicio)
        </dt>
        <dd class="col-sm-7">
            @Html.DisplayFor(model => model.Servicio.Nombre)
        </dd>
    </dl>
    <div>
        <a class="w-100 btn btn-lg  btn-dark" asp-action="Edit" asp-route-id="@Model?.CitaId">Editar</a> 
        <br />
        <br />
        <a class="w-100 btn btn-lg  btn-dark" style="background-color:pink; color: black;" asp-action="Index">Volver a la lista</a>
    </div>
</div>

POS_BeautySalon/POS_BeautySalon/Views/Citas/Edit.cshtml
@model DAL.Cita

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row registration-section">
    <h2>Editar Cita</h2>
    <hr />
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CitaId" />
            <input type="hidden" asp-for="Estado" />
        <div class="form-group">
            <label asp-for="ClienteId" class="control-label"></label>
            <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></select>
            <span asp-validation-for="ClienteId" class="text-danger"></span>
        </div>
            <div class="form-group">
                <label asp-for="ServicioId" class="control-label"></label>
                <select asp-for="ServicioId" class="form-control" asp-items="ViewBag.ServicioId"></select>
                <span asp-validation-for="ServicioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" type="date" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hora" class="control-label"></label>
                <input asp-for="Hora" type="time" class="form-control" />
                <span asp-validation-for="Hora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notas" class="control-label"></label>
                <textarea asp-for="Notas" class="form-control"></textarea>
                <span asp-validation-for="Notas" class="text-danger"></span>
            </div>
            <br />
            <div class="text-center">
            <input type="submit" value="Guardar" class="w-50 btn btn-lg  btn-dark" />
            <br />
           
            @if (User.IsInRole("Estilista"))
            {
                <button type="submit" formaction="@Url.Action("Finalizar", "Citas", new { id = Model.CitaId })" class="w-50 btn btn-lg btn-success">
                    Confirmar cita finalizada
                </button>
            }
            <br />
            <br />
            <a class="w-100 btn btn-lg  btn-dark" style="background-color:pink; color: black;" asp-action="Index">Volver a la lista</a>
            </div>
        </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function finalizarCita() {
            if (confirm("¿Estás seguro de que deseas finalizar esta cita?")) {
                document.getElementById("Estado").value = 0;
                document.forms[0].submit();
            }
        }
    </script>
}

POS_BeautySalon/POS_BeautySalon/Views/Citas/Index.cshtml
@model IEnumerable<DAL.Cita>

@{
    ViewData["Title"] = "Citas";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var citasPasadas = ViewData["CitasPasadas"] as List<DAL.Cita>;
    var citasFuturas = ViewData["CitasFuturas"] as List<DAL.Cita>;
    var citasDelDia = ViewData["CitasDelDia"] as List<DAL.Cita>;
}
<br />
<br />
<p>
    <a asp-action="Create" class="titulos_cat">AGENDAR CITA</a>
</p>
<br />
<div class="home" style="padding: 30px">
    <h2>Citas del Día</h2>
    <br />
    @if (citasDelDia != null && citasDelDia.Any())
    {
        <table>
            <thead>
                <tr>
                    <th>
                        Número de reserva
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Hora)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cliente)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Servicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Notas)
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in citasDelDia)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CitaId)
                        </td>
                        <td>
                            @item.Fecha.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @item.Hora.ToString("hh\\:mm")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cliente.Nombre) @Html.DisplayFor(modelItem => item.Cliente.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Servicio.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Notas)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.CitaId">Editar</a><br />
                            <a asp-action="Details" asp-route-id="@item.CitaId">Detalles</a><br />
                            <a asp-action="Delete" asp-route-id="@item.CitaId">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay citas programadas para hoy.</p>
    }

</div>

<br />
<div class="home" style="padding: 30px">
    <h2>Citas Futuras</h2>
    <br />
    @if (citasFuturas != null && citasFuturas.Any())
    {
        <table>
            <thead>
                <tr>
                    <th>
                        Número de reserva
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Hora)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cliente)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Servicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Notas)
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in citasFuturas)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CitaId)
                        </td>
                        <td>
                            @item.Fecha.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @item.Hora.ToString("hh\\:mm")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cliente.Nombre) @Html.DisplayFor(modelItem => item.Cliente.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Servicio.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Notas)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.CitaId">Editar</a><br />
                            <a asp-action="Details" asp-route-id="@item.CitaId">Detalles</a><br />
                            <a asp-action="Delete" asp-route-id="@item.CitaId">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay citas futuras.</p>
    }
</div>

<br />
<div class="home" style="padding: 30px">
    <h2>Citas Pasadas</h2>
    <br />
    @if (citasPasadas != null && citasPasadas.Any())
    {
        <table>
            <thead>
                <tr>
                    <th>
                        Número de reserva
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Hora)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cliente)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Servicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Notas)
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in citasPasadas)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CitaId)
                        </td>
                        <td>
                            @item.Fecha.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @item.Hora.ToString("hh\\:mm")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cliente.Nombre) @Html.DisplayFor(modelItem => item.Cliente.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Servicio.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Notas)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.CitaId">Editar</a><br />
                            <a asp-action="Details" asp-route-id="@item.CitaId">Detalles</a><br />
                            <a asp-action="Delete" asp-route-id="@item.CitaId">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay citas pasadas.</p>
    }
</div>